### ISSUE TITLE
FedVoc: international money amount and currency

### ISSUE THREAD

**Issue by smals-vea** [belgif/fedvoc#17]
cf. https://github.com/belgif/openapi-money/issues/2

Support international money amounts by defining:
- a Currency type
- a type for the numerical money amount

- [ ] @MarcBruyland Make a proposition draft to determine final naming of the types Currency & money amount

**Comment by pvdbosch** [comment]
like in linked issue, a third vocabulary entry "Money" could be defined as a class with properties currency and amount. But maybe there's another way to represent this in Skos/RDF than a class.

**Comment by smals-vea** [comment]
Lors de la réunion du 30/07/2021, il a été décidé de 

- valider (Standard FedVoc) le concept Currency
- d'améliorer les concepts Amount et MonetaryAmount (Draft FedVoc)

@MarcBruyland , peux-tu harmoniser les définitions entre le concept et le conceptScheme de Currency?
@pvdbosch peux-tu améliorer Amount et MonetaryAmount?

**Comment by pvdbosch** [comment]
Isn't there only a single Currency defined as ConceptScheme in http://publications.europa.eu/resource/authority/currency ? 
I can't find the entry <eupub:currency#id>.

```xml
<rdf:Description rdf:about="http://publications.europa.eu/resource/authority/currency">
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
    <rdfs:label xml:lang="en">Currency</rdfs:label>
    <owl:imports rdf:resource="http://publications.europa.eu/ontology/euvoc"/>
    <ns4:identifier>http://publications.europa.eu/resource/authority/currency</ns4:identifier>
    <!-- ... -->
</rdf:Description>
```

There is a property (but no Concept) "https://schema.org/currency" on schema.org.
Maybe related to discussion Concept vs property on https://github.com/belgif/fedvoc/issues/2#issuecomment-891810504 .

I'd suggest then:

Id | 722
-- | --
Name | Currency
Definition | The Currency authority table is a controlled vocabulary that lists concepts associated with currencies and currency subunits.The concepts included are correlated with the ISO 4217 international standard.The Currency authority table is updated based on the stakeholders’ needs.Contributions to it are accepted following a review made by EU Vocabularies team of the Publications Office of the EU.The Currency authority table is maintained by the Publications Office of the European Union on the EU Vocabularies website. ID: http://publications.europa.eu/resource/authority/currency
Ontology | Generic
Type | ConceptScheme
URI | <eupub:currency>

Id | 723
-- | --
Name | currency
Definition | The currency in which the monetary amount is expressed.
Ontology | Generic
Type | Property
URI | <schema:currency>
Comment | Use of Currency ConceptScheme is recommended (ISO 4217 currency format).

Id | 724
-- | --
Name | MonetaryAmount
Definition | A monetary value or range. This type can be used to describe an amount of money such as $50 USD, or a range as in describing a bank account being suitable for a balance between £1,000 and £1,000,000 GBP, or the value of a salary, etc. It is recommended to use PriceSpecification Types to describe the price of an Offer, Invoice, etc.
Ontology | Generic
Type | Class
URI | <schema:MonetaryAmount>
Comment | Most commonly used with currency (ISO 4217) and value properties.

=> Updated "Comment"
=> data models: add currency and value as properties of MonetaryAmount


Id | TBD (new)
-- | --
Name | value
Definition | The value of the quantitative value or property value node. For QuantitativeValue and MonetaryAmount, the recommended type for values is 'Number'. For PropertyValue, it can be 'Text;', 'Number', 'Boolean', or 'StructuredValue'. Use values from 0123456789 (Unicode 'DIGIT ZERO' (U+0030) to 'DIGIT NINE' (U+0039)) rather than superficially similiar Unicode symbols. Use '.' (Unicode 'FULL STOP' (U+002E)) rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator.
Ontology | Generic
Type | Property
URI | <schema:value>
Comment | When used in MonetaryAmount, do not use any readability separators (spaces, commas).

Id | 725
-- | --
Name | amount
Definition | The amount of money.
Ontology | Generic
Type | Property
Comment | Recommended to express using MonetaryAmount.
URI | <schema:amount>

**Comment by pvdbosch** [comment]
FYI, updated schema draft types in: https://github.com/belgif/openapi-money/issues/2#issuecomment-892542421

**Comment by MarcBruyland** [comment]
Peter's proposal was accepted by the functional workgroup on 2021-10-29.
Fedvoc will be updated accordingly.
