### ISSUE TITLE
New Region(code) in the National Register (Address IT20): 1 position num

### ISSUE THREAD

**Issue by smals-vea** [belgif/fedvoc#8]
Dans le cadre de la nouvelle structure des adresses (BeSt), le Registre national (et donc la BCSS) a choisi d'identifier, dans ces nouveaux schémas de WS, une région sur base d'1 code numérique en 1 position au lieu de suivre la norme ISO-3166-2:BE qui identifie:

- BE-BRU
- BE-VLG
- BE-WAL

Que fait-on au niveau de FedVoc ?

**Comment by pvdbosch** [comment]
I've asked the question within CBSS if there was some specific reason for the one digit code.
What does BOSA do in their BeSt web services that centralize informaiton across the BeSt regional sources?

**Comment by pvdbosch** [comment]
CBSS copies the one-digit codes from NR, there was no other specific reason to use them.

If we standardize on the ISO ones, CBSS could use them, mapped from NR. Because this would be a breaking change, it would have to wait to be included in a new major version of the CBSS person services (probably REST).

**Comment by pvdbosch** [comment]
The ISO codes seem also to be used in the address list (CSV exports) of BOSA: https://opendata.bosa.be/index.nl.html

In FedVoc, I think we could adopt the ISO codes as well, because it's a more internationally recognized standard.

**Comment by MarcBruyland** [comment]
Workgroup decided on 2020-06-26 to use the ISO code (not limited to Belgian region codes).
See https://github.com/belgif/rest-guide/issues/62
